<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    Total result: <?= number_format($total, 0, '.','.'); ?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h3>Posts Trash</h3>
            </div>
            
            <?php if($posts): ?>
            <?php
                $can_delete     = $this->can_i->remove_post_trash;
                $can_restore    = $this->can_i->restore_post_trash;
            ?>
            
            <div class="list-group">
                <?php foreach($posts as $post): ?>
                <div class="list-group-item">
                    
                    <div class="btn-group btn-group-xs pull-right" role="group">
                        <?php if($can_restore): ?>
                        <a href="<?= $this->router->to('adminPostTrashRestore', ['id'=>$post->id], ['ref'=>$reff]) ?>" class="btn btn-default" title="Restore" data-confirm="Restore Confirmation" data-confirm-message="Are you sure want to restore this post?" data-confirm-label="Restore" data-confirm-type="primary">
                            <i class="fa fa-repeat" aria-hidden="true"></i>
                        </a>
                        <?php endif; ?>
                        
                        <?php if($can_delete): ?>
                            <button id="post-<?= $post->id ?>" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-default btn-xs">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="post-<?= $post->id ?>">
                                <li>
                                    <a href="<?= $this->router->to('adminPostTrashRemove', ['id'=>$post->id], ['ref'=>$reff]) ?>" data-confirm="Delete Confirmation" data-confirm-message="Are you sure want to delete this post permanently? This action can't be undone." title="Delete" aria-label="Delete">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Delete
                                    </a>
                                </li>
                            </ul>
                        <?php endif; ?>
                    </div>
                    
                    <h4 class="list-group-item-heading">
                        <?= $post->title ?>
                    </h4>
                    <p class="list-group-item-text small">
                        <span title="Created"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i> <?= $post->created->format('M d, Y H:i') ?></span>
                        &middot;
                        <span title="Updated"><i class="fa fa-calendar-minus-o" aria-hidden="true"></i> <?= $post->updated->format('M d, Y H:i') ?></span>
                        <?php if($post->status == 4): ?>
                        &middot;
                        <span title="Published"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <?= $post->published->format('M d, Y H:i') ?></span>
                        <?php endif; ?>
                        &middot;
                        <span title="Deleted"><i class="fa fa-calendar-times-o" aria-hidden="true"></i> <?= $post->deleted->format('M d, Y H:i') ?></span>
                    </p>
                    <p class="list-group-item-text small">
                        <span title="Writer">
                            <i class="fa fa-user-plus" aria-hidden="true"></i>
                            <?= $post->user->fullname ?>
                        </span>
                        &middot;
                        <span title="Deleter">
                            <i class="fa fa-user-times" aria-hidden="true"></i>
                            <?= $post->deleter->fullname ?>
                        </span>
                        <?php if($post->featured): ?>
                            &middot;
                            <span title="Featured" class="text-success">
                                <i class="fa fa-star" aria-hidden="true"></i>
                                Featured
                            </span>
                        <?php endif; ?>
                        <?php if($post->editor_pick): ?>
                            &middot;
                            <span title="Editor Pick" class="text-warning">
                                <i class="fa fa-check" aria-hidden="true"></i>
                                Editor Pick
                            </span>
                        <?php endif; ?>
                    </p>
                </div>
                <?php endforeach; ?>
            </div>
            
            <?php
                if($pagination)
                    $this->partial('shared/pagination', ['pagination'=>$pagination]);
            ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>